[package]
name = "json_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "json_parser"
path = "src/lib.rs"

[dependencies]
eyre = "0.6.11"
